language: csharp
dist: trusty
sudo: required
solution: ./src/RocketNET/RocketNET.sln
mono: none
dotnet: 2.0.0

before_script:
- dotnet restore ./src/RocketNET/RocketNET.sln

script:
- dotnet build
- dotnet test rocketnet\src\RocketNET\RocketNET.Test\RocketNET.Test.csproj
