image: Visual Studio 2017

before_build:
  - choco install opencover.portable
  - choco install coveralls.io --source https://dotnet.myget.org/F/dotnet-core/api/v2

# version of net core
environment:
    matrix:
        - CLI_VERSION: 2.0.0
    COVERALLS_REPO_TOKEN:  
       secure: 3d+rDxyuGPl4H9R/S/3OBlLWyH8NAncJfr8QfWfMV1XtTT8icBNIalrYietsIlIR

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore ./src/RocketNET/RocketNET.sln
  - ps: dotnet build ./src/RocketNET/RocketNET.sln

test_script:
  - ps: OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\rocketnet\src\RocketNET\RocketNET.Test\RocketNET.Test.csproj" -filter:"+[*]* -[*]*" -output:".\rocketnet_coverage.xml"
  - ps: coveralls.net.exe --opencover coverage.xml -r 3d+rDxyuGPl4H9R/S/3OBlLWyH8NAncJfr8QfWfMV1XtTT8icBNIalrYietsIlIR

version: 0.0.1.{build}

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "rocketnet_coverage.xml" -t 8c7fa0a0-b62e-4fda-8426-a1d22e6df390
