image: Visual Studio 2017

before_build:
- choco install opencover.portable
- choco install codecov

# version of net core
environment:
    matrix:
        - CLI_VERSION: 2.0.0

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore ./src/RocketNET/RocketNET.sln
  - ps: dotnet build ./src/RocketNET/RocketNET.sln

build_script:
  - ps: .\build.ps1
  - OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\rocketnet\src\RocketNET\RocketNET.Core.Test\RocketNET.Core.Test.csproj" -filter:"+[*]* -[*]*" -output:".\rocketnet_coverage.xml"
  - codecov -f .\coverage.xml -t 8c7fa0a0-b62e-4fda-8426-a1d22e6df390

version: 0.0.1.{build}

#test_script:
# - ps: .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:administrator -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\rocketnet\TestLibrary\bin\Debug\TestLibrary.dll -noshadow" -output:"coverage.xml" -filter:"+[*]* -[*]*"
 
#after_test:
#  - ps: |
#      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
#      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
#      bash codecov.sh -f "coverage.xml" -t 8c7fa0a0-b62e-4fda-8426-a1d22e6df390
