image: Visual Studio 2017

before_build:
  - choco install opencover.portable

# version of net core
environment:
    matrix:
        - CLI_VERSION: 2.0.0

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new 
  - ps: dotnet restore ./src/RocketNET/RocketNET.sln
  - ps: dotnet build ./src/RocketNET/RocketNET.sln

test_script:
  - ps: OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\rocketnet\src\RocketNET\RocketNET.Test\RocketNET.Test.csproj" -filter:"+[*]* -[*]*" -output:".\rocketnet_coverage.xml"

version: 0.0.1.{build}

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "rocketnet_coverage.xml" -t 8c7fa0a0-b62e-4fda-8426-a1d22e6df390
